version: '3.7'

services:

  wellwithwaves-front:
    container_name: wellwithwaves-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    expose: 
    - 3000
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true